# Generated by Django 5.2.9 on 2026-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('grocery', 'Grocery'), ('travel', 'Travel'), ('salary', 'Salary'), ('rent', 'Rent'), ('other', 'Other')], max_length=100),
        ),
    ]
