# Generated by Django 5.2.9 on 2026-01-06 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
