# Generated by Django 5.2.9 on 2026-01-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_paymentmethod_expense_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('grocery', 'Grocery'), ('travel', 'Travel'), ('rent', 'Rent'), ('other', 'Other')], max_length=100),
        ),
    ]
