# Generated by Django 5.2.9 on 2026-01-08 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_monthlysalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysalary',
            options={'ordering': ['-month']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('grocery', 'Grocery'), ('travel', 'Travel'), ('rent', 'Rent'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.paymentmethod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
